runtime: nodejs16

env: flex

env_variables:
  DB_USER: "waste-app-user"
  DB_NAME: "waste"
  DB_PASS: "wasteapp101"
  DB_INSTANCE: "fluent-stratum-345612:us-central1:waste-app"
  # TESTVAR: "hehehe"
  # TWILIO_SID: "XYZ1234PBJ"
  # TWILIO_AUTH_TOKEN: "XYZ1234PBJ"
  GOOGLE_CLIENT_ID: "776569245382-gi0gi9vmonbak73nhsocnibq801f95iu.apps.googleusercontent.com"
  # GOOGLE_CLIENT_SECRET: "xyz1234-PBJ"git remote set-url origin link